name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install SSH client
        run: sudo apt-get install openssh-client

      - name: Set Private Key Permissions
        run: chmod 600 /Users/muhammadqasim/.ssh/id_rsa

      - name: Configure SSH key
        env:
          SSH_PRIVATE_KEY: "SHA256:JwFoYsRDQ5EAs9rKhSjnritC/5JwlS0470ctZ+vCRIk qasimriaz814@gmail.com"
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 149.28.215.39 >> ~/.ssh/authorized_keys
        

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: "SHA256:Qt00LqPs5YGY5sdM24R1fSJvJI0QLyYyrYyBjXltirg qasimriaz814@gmail.com"

          

      - name: Deploy React App
        run: |
          ssh root@149.28.215.39 'bash -s' < deploy.sh
